#!/bin/sh

# Install coreutils if not already installed
apt install -y coreutils

# Try to access Google with a timeout of 2 seconds
if timeout 2 curl -s -o /dev/null https://www.google.com; then
    # If successful (no timeout), do nothing
    :
else
    # If timeout, execute action A
    echo -e "\033[1;31mTimeout: Unable to access Google, executing action A\033[0m"
    echo -e "\033[1;34m******************* Setting apt mirror: TSINGHUA & USTC ******************\033[0m"

    # Replace with Tsinghua mirror
    sed -i 's@//.*archive.ubuntu.com@//mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/ubuntu.sources

    # Update package list and install necessary tools
    apt update -y --fix-missing
    apt install -y --no-install-recommends curl wget ca-certificates

    # Replace HTTP with HTTPS
    sed -i 's/http:/https:/g' /etc/apt/sources.list.d/ubuntu.sources
    apt update -y

    echo -e "\033[1;32m******************* apt mirror set: TSINGHUA & USTC ******************\033[0m"
fi