#!/bin/sh
# apt update -y 
# curl -sSL https://cdn.jsdelivr.net/gh/HYwooo/install@master/install | sudo sh
apt update -y --fix-missing && apt install -y --no-install-recommends curl wget ca-certificates && sed -i 's/http:/https:/g' /etc/apt/sources.list.d/ubuntu.sources && apt update -y
##
apt install -y gcc g++ rustup && rustup default stable
mkdir -p ~/.cargo && mkdir -p ~/.cargo/env && echo "[source.crates-io]\nreplace-with = \"tuna-sparse\"\n\n[source.tuna-sparse]\nregistry = \"sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/\"" > ~/.cargo/config.toml
##
apt install -y git zsh fonts-powerline
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/carloscuesta/materialshell.git ~/.oh-my-zsh/custom/themes/materialshell
sed -i 's/^ZSH_THEME=.*/ZSH_THEME="materialshell\/materialshell"/' ~/.zshrc
sed -i 's/^plugins=.*/plugins=(git rust python zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
#eval "$(curl https://get.x-cmd.com)"
#echo "[ ! -f \"\$HOME/.x-cmd.root/X\" ] || . \"\$HOME/.x-cmd.root/X\" " >> ~/.zshrc
echo ". \"\$HOME/.cargo/env\"" >> ~/.zshrc && echo "export TERM=xterm-256color" >> ~/.zshrc
chsh -s $(which zsh)
